# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import point_registration_pb2 as point__registration__pb2


class PointRegisteringStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerPoints = channel.unary_unary(
                '/PointRegistering/registerPoints',
                request_serializer=point__registration__pb2.input.SerializeToString,
                response_deserializer=point__registration__pb2.output.FromString,
                )


class PointRegisteringServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registerPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointRegisteringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.registerPoints,
                    request_deserializer=point__registration__pb2.input.FromString,
                    response_serializer=point__registration__pb2.output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PointRegistering', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PointRegistering(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registerPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PointRegistering/registerPoints',
            point__registration__pb2.input.SerializeToString,
            point__registration__pb2.output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
