# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point_registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='point_registration.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18point_registration.proto\"V\n\x05input\x12\x1c\n\x0bpoint_set_1\x18\x01 \x03(\x0b\x32\x07.vector\x12\x1c\n\x0bpoint_set_2\x18\x02 \x03(\x0b\x32\x07.vector\x12\x11\n\talgorithm\x18\x03 \x01(\t\"c\n\x06output\x12\x0e\n\x06status\x18\x01 \x01(\t\x12$\n\x0frotation_matrix\x18\x02 \x03(\x0b\x32\x0b.matrix_row\x12#\n\x12translation_vector\x18\x03 \x01(\x0b\x32\x07.vector\"\x19\n\nmatrix_row\x12\x0b\n\x03row\x18\x01 \x03(\x02\"\x1d\n\x06vector\x12\x13\n\x0bvector_data\x18\x01 \x03(\x02\x32\x37\n\x10PointRegistering\x12#\n\x0eregisterPoints\x12\x06.input\x1a\x07.output\"\x00\x62\x06proto3'
)




_INPUT = _descriptor.Descriptor(
  name='input',
  full_name='input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='point_set_1', full_name='input.point_set_1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point_set_2', full_name='input.point_set_2', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='input.algorithm', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=114,
)


_OUTPUT = _descriptor.Descriptor(
  name='output',
  full_name='output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='output.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_matrix', full_name='output.rotation_matrix', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translation_vector', full_name='output.translation_vector', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=215,
)


_MATRIX_ROW = _descriptor.Descriptor(
  name='matrix_row',
  full_name='matrix_row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='matrix_row.row', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=242,
)


_VECTOR = _descriptor.Descriptor(
  name='vector',
  full_name='vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_data', full_name='vector.vector_data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=273,
)

_INPUT.fields_by_name['point_set_1'].message_type = _VECTOR
_INPUT.fields_by_name['point_set_2'].message_type = _VECTOR
_OUTPUT.fields_by_name['rotation_matrix'].message_type = _MATRIX_ROW
_OUTPUT.fields_by_name['translation_vector'].message_type = _VECTOR
DESCRIPTOR.message_types_by_name['input'] = _INPUT
DESCRIPTOR.message_types_by_name['output'] = _OUTPUT
DESCRIPTOR.message_types_by_name['matrix_row'] = _MATRIX_ROW
DESCRIPTOR.message_types_by_name['vector'] = _VECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

input = _reflection.GeneratedProtocolMessageType('input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'point_registration_pb2'
  # @@protoc_insertion_point(class_scope:input)
  })
_sym_db.RegisterMessage(input)

output = _reflection.GeneratedProtocolMessageType('output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'point_registration_pb2'
  # @@protoc_insertion_point(class_scope:output)
  })
_sym_db.RegisterMessage(output)

matrix_row = _reflection.GeneratedProtocolMessageType('matrix_row', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX_ROW,
  '__module__' : 'point_registration_pb2'
  # @@protoc_insertion_point(class_scope:matrix_row)
  })
_sym_db.RegisterMessage(matrix_row)

vector = _reflection.GeneratedProtocolMessageType('vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'point_registration_pb2'
  # @@protoc_insertion_point(class_scope:vector)
  })
_sym_db.RegisterMessage(vector)



_POINTREGISTERING = _descriptor.ServiceDescriptor(
  name='PointRegistering',
  full_name='PointRegistering',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=275,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerPoints',
    full_name='PointRegistering.registerPoints',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POINTREGISTERING)

DESCRIPTOR.services_by_name['PointRegistering'] = _POINTREGISTERING

# @@protoc_insertion_point(module_scope)
